version: '3.8'  # Updated version

services:
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    image: ${{ IMAGE_1 }}

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    image: ${{ IMAGE_2 }}
